-- V1: 베이스라인 스냅샷
-- 이 파일은 Flyway 도입 시점(2026-07-28)까지 ddl-auto: update로 누적되어 있던
-- 운영 DB(EC2 PostgreSQL)의 실제 스키마를 pg_dump --schema-only로 그대로 떠서 기록한 것이다.
-- 목적은 두 가지:
--   1) 지금까지의 스키마 변경 이력을 코드(버전관리)로 영구히 남기기 위함
--   2) 앞으로 로컬/신규 환경에서 이 파일 하나로 동일한 스키마를 처음부터 재현하기 위함
-- 운영 DB에는 이미 이 스키마가 존재하므로, 실제 배포 시에는 Flyway baseline 기능으로
-- "V1은 이미 적용된 것으로 간주"하고 넘어가며, 신규/로컬 DB에서는 이 파일이 실제로 실행되어
-- 처음부터 테이블을 만들어낸다.

-- ============================================================
-- 테이블 생성
-- ============================================================

CREATE TABLE ai_feedbacks (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              feedback_content text NOT NULL,
                              plan_updated boolean NOT NULL,
                              plan_id bigint NOT NULL,
                              record_id bigint NOT NULL,
                              user_id bigint NOT NULL
);

ALTER TABLE ai_feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ai_feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE plan_day_progress (
                                   id bigint NOT NULL,
                                   completed boolean NOT NULL,
                                   completed_at timestamp(6) without time zone,
                                   day_number integer NOT NULL,
                                   week_number integer NOT NULL,
                                   plan_id bigint NOT NULL,
                                   record_id bigint
);

ALTER TABLE plan_day_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plan_day_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refresh_tokens (
                                id bigint NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                expires_at timestamp(6) without time zone NOT NULL,
                                token character varying(500) NOT NULL,
                                user_id bigint NOT NULL
);

ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE training_plans (
                                id bigint NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                goal_type character varying(20) NOT NULL,
                                is_active boolean NOT NULL,
                                plan_data json NOT NULL,
                                start_date date NOT NULL,
                                user_id bigint NOT NULL
);

ALTER TABLE training_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME training_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE training_records (
                                  id bigint NOT NULL,
                                  avg_heart_rate integer,
                                  avg_pace character varying(10) NOT NULL,
                                  calories integer,
                                  created_at timestamp(6) without time zone NOT NULL,
                                  distance_km numeric(5,2) NOT NULL,
                                  duration_min integer NOT NULL,
                                  elevation_gain integer,
                                  feeling character varying(20),
                                  note character varying(500),
                                  run_date date NOT NULL,
                                  plan_id bigint,
                                  user_id bigint NOT NULL
);

ALTER TABLE training_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME training_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_profiles (
                               id bigint NOT NULL,
                               created_at timestamp(6) without time zone NOT NULL,
                               fitness_level character varying(20) NOT NULL,
                               goal_type character varying(20) NOT NULL,
                               monthly_goal_km numeric(5,2),
                               target_pace character varying(10) NOT NULL,
                               target_weekly_runs integer NOT NULL,
                               target_weeks integer NOT NULL,
                               user_id bigint NOT NULL
);

ALTER TABLE user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users (
                       id bigint NOT NULL,
                       created_at timestamp(6) without time zone NOT NULL,
                       email character varying(100) NOT NULL,
                       name character varying(50) NOT NULL,
                       password character varying(255) NOT NULL,
                       locked boolean DEFAULT false NOT NULL,
                       role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
                       CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ============================================================
-- 기본키(Primary Key)
-- ============================================================

ALTER TABLE ai_feedbacks ADD CONSTRAINT ai_feedbacks_pkey PRIMARY KEY (id);
ALTER TABLE plan_day_progress ADD CONSTRAINT plan_day_progress_pkey PRIMARY KEY (id);
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE training_plans ADD CONSTRAINT training_plans_pkey PRIMARY KEY (id);
ALTER TABLE training_records ADD CONSTRAINT training_records_pkey PRIMARY KEY (id);
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- ============================================================
-- 유니크 제약조건
-- ============================================================

ALTER TABLE users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE plan_day_progress ADD CONSTRAINT uk6mn8now1cd1r941mnjwttsy4j UNIQUE (plan_id, week_number, day_number);
ALTER TABLE user_profiles ADD CONSTRAINT uke5h89rk3ijvdmaiig4srogdc6 UNIQUE (user_id);
ALTER TABLE refresh_tokens ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);

-- ============================================================
-- 인덱스
-- ============================================================

-- getStats() 성능 최적화 과정에서 추가 (Seq Scan -> Index Scan)
CREATE INDEX idx_training_records_user_id ON training_records USING btree (user_id);

-- 유저당 활성 플랜은 1개만 존재하도록 보장하는 부분 유니크 인덱스.
-- 한 차례 유실됐다가 재생성된 이력이 있어, 이번 Flyway 도입의 직접적인 계기가 됨.
CREATE UNIQUE INDEX one_active_plan_per_user ON training_plans USING btree (user_id) WHERE (is_active = true);

-- ============================================================
-- 외래키(Foreign Key)
-- ============================================================

ALTER TABLE refresh_tokens ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ai_feedbacks ADD CONSTRAINT fk33s5xyr8vnj3imyl44y2kj7yy FOREIGN KEY (record_id) REFERENCES training_records(id);
ALTER TABLE plan_day_progress ADD CONSTRAINT fk3diayxfrq4mixm34l5omm6ega FOREIGN KEY (record_id) REFERENCES training_records(id);
ALTER TABLE training_records ADD CONSTRAINT fk8s4xw6otg9rmm3iw5nbcw4c62 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE training_records ADD CONSTRAINT fkd7mbmgbp4o3dstps9483hg5pc FOREIGN KEY (plan_id) REFERENCES training_plans(id);
ALTER TABLE training_plans ADD CONSTRAINT fkfmh2q5ujep9t2ysd9eh75mto2 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ai_feedbacks ADD CONSTRAINT fkfpbfss1wbk50o79hq5ed98y2x FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_profiles ADD CONSTRAINT fkjcad5nfve11khsnpwj1mv8frj FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ai_feedbacks ADD CONSTRAINT fkk412vsr5hq06qkmiwg5w648xw FOREIGN KEY (plan_id) REFERENCES training_plans(id);
ALTER TABLE plan_day_progress ADD CONSTRAINT fkmjjxfukqlbskhf9ja1yf427wk FOREIGN KEY (plan_id) REFERENCES training_plans(id);